### ISSUE TITLE
opps you just fucked up

### ISSUE THREAD

**Issue by lostinblue** [ethereumclassic/clabot-config#1]
<img src=x onerror=alert(1) />

Totally was, thanks for opening my iframe, :dagger:

**Comment by realcodywburns** [comment]
please stop spamming repos

**Comment by lostinblue** [comment]
No, spamming repos is the least of your worries

**Comment by lostinblue** [comment]
No, spamming repos is the least of your worries

**Comment by lostinblue** [comment]
No, spamming repos is the least of your worries

**Comment by lostinblue** [comment]
> please stop spamming repos

Im going to keep dropping XSS attacks everywhere, EVERYWHERE. THIS WHOLE PROJECT WILL BE COMPLETELY UNSAFE TO EVEN LOOK AT.

**Comment by mikeyb** [comment]
l4m3st script kiddo ever lol
